#!/usr/bin/env node
/**
 * claude-comm installer — wires the bus into a hub-and-spoke project.
 *
 *   node install.mjs <project-root> [--check]
 *
 * It is IDEMPOTENT and NON-DESTRUCTIVE: existing `.claude/settings.json` keys and
 * unrelated hooks are preserved; only a hook whose command mentions `comm-hook`
 * is replaced. `--check` reports drift without writing (so it can be a gate).
 *
 * Path strategy, measured rather than assumed: Claude Code runs hooks with both
 * cwd and $CLAUDE_PROJECT_DIR set to the repo root. We still resolve the bus from
 * the STUB's own location (import.meta.url), so nothing breaks if the project is
 * moved, cloned, or a hook is invoked from a subdirectory.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync, copyFileSync } from "node:fs"
import { join, dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const HERE = dirname(fileURLToPath(import.meta.url))
const CHECK = process.argv.includes("--check")
const ROOT = resolve(process.argv[2] || process.cwd())

const STUB = `#!/usr/bin/env node
// GENERATED by claude-comm install.mjs — do not edit.
// Resolves the bus from THIS FILE's location, then forwards the hook payload.
import { existsSync } from "node:fs"
import { join, dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { spawnSync } from "node:child_process"

let dir = resolve(dirname(fileURLToPath(import.meta.url)))
let bus = null
for (;;) {
\tconst c = join(dir, ".comm", "bin", "comm.mjs")
\tif (existsSync(c)) { bus = c; break }
\tconst up = dirname(dir)
\tif (up === dir) break
\tdir = up
}
// A missing bus must never break the session.
if (!bus) process.exit(0)
const r = spawnSync(process.execPath, [bus, "hook", ...process.argv.slice(2)], { stdio: "inherit" })
process.exit(r.status ?? 0)
`

function readJson(p, fallback) {
	try { return JSON.parse(readFileSync(p, "utf8")) } catch { return fallback }
}

/** Merge our two hooks into a settings object without disturbing anything else. */
function withHooks(settings) {
	const s = { ...settings }
	s.hooks = { ...(s.hooks || {}) }
	for (const [event, verb] of [["Stop", "stop"], ["SessionStart", "session-start"]]) {
		const keep = (s.hooks[event] || []).filter(
			(g) => !(g.hooks || []).some((h) => String(h.command || "").includes("comm-hook"))
		)
		s.hooks[event] = [
			...keep,
			{ hooks: [{ type: "command", command: `node "$CLAUDE_PROJECT_DIR/.claude/comm-hook.mjs" ${verb}` }] },
		]
	}
	return s
}

function write(path, content, results) {
	const cur = existsSync(path) ? readFileSync(path, "utf8") : null
	if (cur === content) { results.ok.push(path); return }
	if (CHECK) { results.drift.push(path); return }
	mkdirSync(dirname(path), { recursive: true })
	writeFileSync(path, content)
	results.wrote.push(path)
}

// ── 1. the bus itself ───────────────────────────────────────────────────────
const commDir = join(ROOT, ".comm")
const cfgPath = join(commDir, "config.json")
if (!existsSync(cfgPath)) {
	console.error(`✗ no .comm/config.json at ${ROOT}\n  run:  cd ${ROOT} && node ${join(HERE, "bin/comm.mjs")} init`)
	process.exit(1)
}
const cfg = readJson(cfgPath)
const results = { wrote: [], ok: [], drift: [] }

if (!CHECK) mkdirSync(join(commDir, "bin"), { recursive: true })
const busSrc = readFileSync(join(HERE, "bin", "comm.mjs"), "utf8")
write(join(commDir, "bin", "comm.mjs"), busSrc, results)

// ── 2. per-agent stub + hooks ───────────────────────────────────────────────
for (const [id, relPath] of Object.entries(cfg.agents)) {
	const agentRoot = resolve(ROOT, relPath)
	if (!existsSync(agentRoot)) { console.error(`  ⚠ ${id}: ${agentRoot} does not exist — skipped`); continue }

	write(join(agentRoot, ".claude", "comm-hook.mjs"), STUB, results)

	const sPath = join(agentRoot, ".claude", "settings.json")
	const merged = withHooks(readJson(sPath, {}))
	write(sPath, JSON.stringify(merged, null, 2) + "\n", results)

	if (!CHECK) mkdirSync(join(commDir, "inbox", id), { recursive: true })
}

// ── 3. keep live state out of git ───────────────────────────────────────────
const giPath = join(ROOT, ".gitignore")
if (existsSync(giPath)) {
	const gi = readFileSync(giPath, "utf8")
	if (!/^\.comm\/?$/m.test(gi)) {
		if (CHECK) results.drift.push(giPath)
		else { writeFileSync(giPath, gi.replace(/\n*$/, "\n") + "\n# claude-comm live state (regenerate with install.mjs)\n.comm/\n"); results.wrote.push(giPath) }
	} else results.ok.push(giPath)
}

// ── report ──────────────────────────────────────────────────────────────────
if (CHECK) {
	if (results.drift.length) {
		console.error(`✗ claude-comm: ${results.drift.length} file(s) out of date:`)
		for (const p of results.drift) console.error(`    ${p.replace(ROOT + "/", "")}`)
		console.error(`\n  fix:  node ${join(HERE, "install.mjs")} ${ROOT}`)
		process.exit(1)
	}
	console.log(`✓ claude-comm: ${results.ok.length} file(s) in sync across ${Object.keys(cfg.agents).length} agents`)
} else {
	console.log(`✓ claude-comm installed at ${ROOT}`)
	console.log(`  agents:  ${Object.keys(cfg.agents).join(", ")}`)
	console.log(`  wrote:   ${results.wrote.length} file(s)${results.ok.length ? `  (${results.ok.length} already current)` : ""}`)
	console.log(`\n  Hooks take effect in each agent's NEXT session — a running one has already loaded its settings.`)
}
