#!/usr/bin/env node
/**
 * claude-comm installer — wires the bus into a hub-and-spoke project.
 *
 *   node install.mjs <project-root> [--check]
 *
 * It is IDEMPOTENT and NON-DESTRUCTIVE: existing `.claude/settings.json` keys and
 * unrelated hooks are preserved; only a hook whose command mentions `comm-hook`
 * is replaced. `--check` reports drift without writing (so it can be a gate).
 *
 * Path strategy, measured rather than assumed: Claude Code runs hooks with both
 * cwd and $CLAUDE_PROJECT_DIR set to the repo root. We still resolve the bus from
 * the STUB's own location (import.meta.url), so nothing breaks if the project is
 * moved, cloned, or a hook is invoked from a subdirectory.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync, copyFileSync, renameSync, unlinkSync } from "node:fs"
import { join, dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { randomBytes } from "node:crypto"
// Only for the git question below: this file already spawns nothing else, and it is the
// installer rather than the bus, so A21's no-child_process rule does not reach it.
import { spawnSync } from "node:child_process"

const HERE = dirname(fileURLToPath(import.meta.url))
const CHECK = process.argv.includes("--check")
const ROOT = resolve(process.argv[2] || process.cwd())

const STUB = `#!/usr/bin/env node
// GENERATED by claude-comm install.mjs — do not edit.
// Resolves the bus from THIS FILE's location, then forwards the hook payload.
import { existsSync, readFileSync, readdirSync, readlinkSync, writeFileSync } from "node:fs"
import { join, dirname, resolve, basename } from "node:path"
import { fileURLToPath, pathToFileURL } from "node:url"
import { spawnSync } from "node:child_process"

let dir = resolve(dirname(fileURLToPath(import.meta.url)))
// This stub lives at <agentRoot>/.claude/comm-hook.mjs, one per agent, so its own
// location IS this agent's identity. The hook payload's cwd is NOT: it follows the
// Bash tool's working directory, so a leader that cds into an expert's repo during
// a turn would otherwise be identified as that expert and drain its inbox.
const agentRoot = dirname(dir)

/**
 * THE SESSION THIS HOOK RECORDS MUST BE A SESSION IN THIS PROJECT.
 *
 * \`sessionPid()\` walks to the nearest \`claude\` ancestor, which is right when the hook is
 * fired BY that session and wrong the moment anything else fires it - a test suite, an
 * operator reproducing a bug, an agent running another project's stub by hand. Then the
 * walk reaches the CALLER's session and this hook writes that session's registry entry to
 * point at a transcript from somewhere else. Measured five times on 2026-09-04, most
 * recently as \`pid 820277 -> fake.jsonl (stop)\` in the operator's own boot report, green.
 *
 * The invariant is small and exact: I am a hook belonging to a project, so the session I
 * resolve must be running inside that project. When it is not, something is firing me on
 * behalf of a session I do not speak for, and the only safe act is to record nothing.
 */
const ownsSession = (pid) => {
	try {
		const cwd = readlinkSync(\`/proc/\${pid}/cwd\`)
		return cwd === projectRoot || cwd.startsWith(projectRoot + "/")
	} catch { return false }
}
let bus = null, projectRoot = null
for (;;) {
	const c = join(dir, ".comm", "bin", "comm.mjs")
	if (existsSync(c)) { bus = c; projectRoot = dir; break }
	const up = dirname(dir)
	if (up === dir) break
	dir = up
}
// A missing bus must never break the session.
if (!bus) process.exit(0)

const forward = (input) => spawnSync(process.execPath,
	[bus, "hook", ...process.argv.slice(2), "--agent-root", agentRoot],
	input === null ? { stdio: "inherit" } : { input, stdio: ["pipe", "inherit", "inherit"] })

// STOP. Delivery is unchanged in substance - same bus, same arguments - but the payload
// is now read here rather than inherited, because the registry needs a SECOND WITNESS.
//
// G2 (review #5): a SessionStart that never REACHED record() - module missing, module
// unloadable, runtime dir unwritable, hook killed during delivery - leaves the previous
// entry standing, and after a /clear that entry names a session that has ended. Nothing
// in the entry can reveal it: pid, boot id and start tick all still match, it is the same
// process. \`Stop\` is the only thing on this machine that is handed the LIVE transcript at
// every turn boundary, so it is the only thing that can heal those paths - and it heals
// them within one turn instead of never.
//
// The ledger is deliberately NOT here: it records STARTS, and a start is not a turn
// boundary. The registry work is a lookup and a string compare, and it writes only when
// the transcript actually differs - once per session, plus once after a clear.
if (process.argv[2] !== "session-start") {
	let stopRaw = ""
	try { stopRaw = readFileSync(0, "utf8") } catch {}
	const stopped = forward(stopRaw)
	try {
		const reg = join(dirname(bus), "session-registry.mjs")
		if (existsSync(reg)) {
			const sp = JSON.parse(stopRaw || "{}")
			if (typeof sp.transcript_path === "string" && sp.transcript_path) {
				const m = await import(pathToFileURL(reg).href)
				const who = m.sessionPid()
				const r = ownsSession(who)
					? m.refresh({ pid: who, transcript: sp.transcript_path, agent: null, source: "stop" })
					: { ok: true, unchanged: true }
				// Silent on the common path. A turn boundary that printed a line every time
				// would be a warning nobody reads; this speaks only when it CHANGED something
				// and the change failed, which is the state that matters.
				if (!r.ok && !r.unchanged) process.stderr.write(\`claude-comm: could not refresh the session registry (\${r.why}).\\n\`)
			}
		}
	} catch { /* an instrument must never break a turn boundary */ }
	// THE DOORBELL. Mail lands at the recipient's TURN BOUNDARY, so an agent that is alive
	// but idle never receives it - measured over 26 real deliveries as a leader->expert
	// median of 1462 s. Nothing here delivers anything: it makes an idle session take a
	// turn, and that turn's own Stop hook runs the delivery that is already gated.
	//
	// Cheap first, always: a readdir of the inboxes. wake.mjs is only spawned when
	// something is actually waiting for somebody else, so the common turn boundary pays
	// one directory listing and nothing more. It never affects this turn's exit code.
	try {
		const wake = join(dirname(bus), "wake.mjs")
		const ibx = join(projectRoot, ".comm", "inbox")
		let waiting = false
		for (const a of readdirSync(ibx)) {
			try { if (readdirSync(join(ibx, a)).some((f) => f.endsWith(".json"))) { waiting = true; break } } catch {}
		}
		if (waiting && existsSync(wake)) {
			spawnSync(process.execPath, [wake, "--root", projectRoot], { timeout: 10000, stdio: "ignore" })
		}
	} catch { /* a doorbell must never break a turn boundary */ }
	process.exit(stopped.status ?? 0)
}

// SESSION-START. The payload can be read only ONCE and the bus is no longer its only
// consumer, so this stub reads it and hands the bytes on.
let raw = ""
try { raw = readFileSync(0, "utf8") } catch {}

// DELIVERY FIRST, and its status is this hook's status. Everything below is an
// instrument: it may not delay delivery, may not fail it, and may not change one byte
// of what the harness sees.
const delivered = forward(raw)

try {
	let p = {}
	try { p = JSON.parse(raw) } catch {}
	const binDir = dirname(bus)
	const tp = typeof p.transcript_path === "string" ? p.transcript_path : ""
	// The NAME comes from the bus, which is the one place identity is resolved. A
	// ledger keyed on a name this stub had guessed for itself would disagree with the
	// delivery log about who did what, and the ledger counts a \`mislabelled\` row for
	// exactly that reason. "unnamed" matches what boot records for an off-bus session:
	// a session that cannot be named is still a session that can author a defect.
	let agent = "unnamed"
	try {
		const w = spawnSync(process.execPath, [bus, "whoami", "--agent-root", agentRoot],
			{ cwd: agentRoot, encoding: "utf8", timeout: 5000 })
		if (w.status === 0 && String(w.stdout).trim()) agent = String(w.stdout).trim()
	} catch {}

	// The registry: pid -> the transcript this session is writing NOW. An import rather
	// than a spawn, because it is one function call and cannot fail slowly. Without it
	// a context sensor answers with the session this process was LAUNCHED as, which
	// after a /clear is a dead one. FINDINGS.md#clear-blind
	// The result is READ, not dropped. This file's own contract says a registry that
	// silently did not write reads later as a machine with no sessions on it - and review
	// #5 found the only field caller discarding that reason inside a bare catch, which is
	// the enabling condition for a stale entry answering as if it were fresh. stderr,
	// never stdout: stdout carries the hook's JSON contract and one extra byte there
	// breaks delivery. record() is called even with NO transcript_path, because its first
	// act is to invalidate the entry this pid already had.
	try {
		const reg = join(binDir, "session-registry.mjs")
		if (existsSync(reg)) {
			const m = await import(pathToFileURL(reg).href)
			const sp = m.sessionPid()
			if (!ownsSession(sp)) throw new Error(\`the session I resolved (pid \${sp}) is not running inside \${projectRoot}; recording nothing\`)
			const r = m.record({ pid: sp, transcript: tp, agent, source: p.source })
			if (!r.ok) process.stderr.write(\`claude-comm: this session is NOT in the session registry (\${r.why}). \`
				+ \`A context reading by pid will refuse for it\${r.invalidated ? "" : ", and a previous entry may still stand"}.\\n\`)
		} else {
			process.stderr.write("claude-comm: session-registry.mjs is not installed beside the bus, so this session could not be recorded AND ANY PREVIOUS ENTRY FOR THIS PID STILL STANDS - a context reading by pid may answer for a session that has ended.\\n")
		}
	} catch (e) {
		process.stderr.write(\`claude-comm: the session registry could not be loaded (\${(e && e.message) || e}), so this session could not be recorded AND ANY PREVIOUS ENTRY FOR THIS PID STILL STANDS - a context reading by pid may answer for a session that has ended.\\n\`)
	}

	// IS THE LIVE BUS STATE IN THIS PROJECT'S GIT? Measured 2026-09-04: the ~/Dev/work
	// leader put his repo under git and wrote a careful .gitignore — against the things he
	// was thinking about. In his own words, *".comm/ did not exist in my head as a category,
	// so it did not exist in the file"*, and six files of live state were committed: the
	// delivery log, four delivered messages, his config. Nothing told him. install.mjs
	// appends the ignore rule, but it runs ONCE and a .gitignore rewritten afterwards
	// silently undoes it — which is exactly what happened.
	//
	// So this asks the only question with no false positive: are files under .comm/ TRACKED?
	// Not "is there an ignore rule" — a rule can live in a parent .gitignore, in
	// .git/info/exclude, or in a global core.excludesFile, and a check on the rule would cry
	// wolf in every one of those. Tracked-or-not is the defect itself.
	//
	// WHERE the repository is — not whether one begins exactly here. Review #6 F7: this
	// asked \`existsSync(join(projectRoot, ".git"))\`, which is the one question git never
	// asks: \`git ls-files\` walks UP. Demonstrated by the reviewer — a repo at repo/ with the
	// bus installed at repo/sub/, seven files of live state tracked, and this guard silent.
	// The comment above claimed "the only question with no false positive". That was true,
	// and it had a false NEGATIVE it did not name, in the configuration a field project is
	// most likely to be in: a bus living inside a larger repository.
	//
	// WALKED, not spawned. The point of the old existsSync was that a project outside git
	// pays no process at session start, and \`git rev-parse\` would cost one in every project
	// on every start, repository or not. The walk buys the correct answer at the old price.
	let gitRoot = null
	try {
		let d = projectRoot
		for (;;) {
			if (existsSync(join(d, ".git"))) { gitRoot = d; break }
			const up = dirname(d)
			if (up === d) break
			d = up
		}
	} catch { gitRoot = null }
	try {
		if (gitRoot) {
			const g = spawnSync("git", ["ls-files", "--", ".comm"],
				{ cwd: projectRoot, encoding: "utf8", timeout: 5000 })
			// The separator below is written with a DOUBLED backslash on purpose. This string is
			// built inside install.mjs's STUB template literal, so a single-backslash escape is
			// resolved when the stub is WRITTEN, not when it runs — a newline escape becomes a
			// real line break inside a string literal, and a string literal with a line break in
			// it does not parse. Measured while adding this guard: the generated hook became a
			// SyntaxError, so EVERY hook path in every project exited 1 — the bus dead in exactly
			// the way its first rule forbids — and the suite reported it as "A5 corrupt config is
			// inert", a case about something else entirely. Same trap for any escape added here.
			const tracked = String(g.stdout || "").split("\\n").filter(Boolean)
			if (tracked.length) {
				process.stderr.write(
					\`claude-comm: \${tracked.length} file(s) of LIVE BUS STATE are committed to this project's git \` +
					\`(\${tracked.slice(0, 3).join(", ")}\${tracked.length > 3 ? ", …" : ""}).\\n\` +
					\`  .comm/ is inboxes, a delivery log and a lifecycle ledger - it changes every turn, it is per-machine, \` +
					\`and committing it puts another agent's mail in your history.\\n\` +
					\`  Fix:  git rm -r --cached .comm/   then add a line '.comm/' to .gitignore\\n\` +
					\`  Why:  \${join(projectRoot, ".comm", "README.md")}\\n\`)
			}
		}
	} catch { /* a guard must never break a session */ }

	// A NOTICE IS NOT READ BECAUSE IT IS THERE — IT IS READ WHEN SOMEBODY SAYS IT IS NOT.
	//
	// Measured 2026-09-04 by the leader of ~/Dev/work, and it is his sentence: the notice had
	// been sitting in his repository since that morning, and what made him open it was a
	// message telling him nobody had. He also measured what reading it cost - 84 lines, about
	// 4.2 KB, one read - so the cheap half was never the problem. Therefore SessionStart names
	// it ONCE per project, and then never again.
	//
	// A marker beside the notice, not a timer and not every session: a line printed at every
	// start is a line nobody reads, which is the failure this file keeps finding in its own
	// rows. If the marker cannot be written the line comes back next start - noisy, and
	// honest, in that order.
	//
	// NO BACKTICKS ANYWHERE ABOVE. This comment lives inside install.mjs's STUB template
	// literal, so one of them would end the template and the generated hook would not parse -
	// which is exactly what happened while writing this block, and it is the trap the
	// git-guard comment 60 lines up already warns about for backslashes.
	try {
		const seen = join(projectRoot, ".comm", ".notice-seen")
		if (!existsSync(seen)) {
			process.stderr.write(\`claude-comm: this project is on a message bus. What that means, and the one thing not to do: \${join(projectRoot, ".comm", "README.md")} — said once, not again.\\n\`)
			writeFileSync(seen, new Date().toISOString() + "\\n")
		}
	} catch { /* a notice must never break a session */ }

	// The ledger: the control arm for "did the fifteen minutes after a restart cost us
	// a defect". It records into THIS project, beside this project's bus, because this
	// is where the restarts being measured actually happen. Read it back with
	// \`node bin/ledger.mjs --root <this project>\`.
	try {
		const led = join(binDir, "ledger.mjs")
		if (existsSync(led) && p.source && tp) {
			// THE SIGNAL THAT CROSSES THE RESTART, claimed here and nowhere else. At this
			// hook a relaunch and a cold start are the same event — \`source\` is "startup"
			// for both — so without this the reboot arm of the experiment is not
			// under-filled, it is UNREACHABLE. FINDINGS.md#reboot-signal
			//
			// Claimed INSIDE the guard that records, so a signal is never consumed by a
			// hook that was not going to write a start: a one-shot note taken by a path
			// that then records nothing is a reboot silently filed as cold.
			let sig = []
			try {
				const rs = join(binDir, "restart-signal.mjs")
				if (existsSync(rs)) {
					const m = await import(pathToFileURL(rs).href)
					const c = m.claim({ root: projectRoot, agent })
					if (!c.ok) {
						// Never silent. A signal that could not be read is a restart about to be
						// recorded as a cold start, which is the exact defect this mechanism exists
						// to remove — and a bare catch here would hide it forever.
						process.stderr.write(\`claude-comm: a restart signal for \${agent} could not be claimed (\${c.why}); this start is being recorded as COLD.\\n\`)
					} else if (c.signal) {
						// Measurements only. Whether this age still counts is the ledger's
						// \`classify()\` to decide, so the rule stays correctable over records
						// already written. An age that could not be measured is OMITTED rather
						// than sent as a placeholder: the ledger refuses a non-numeric flag, and
						// refusing would cost the whole start record.
						if (c.signal.prev_session) sig.push("--prev-session", String(c.signal.prev_session))
						sig.push("--signal-src", String(c.signal.by || "unknown"))
						if (Number.isFinite(c.age_s)) sig.push("--signal-age", String(c.age_s))
						if (Number.isFinite(c.signal.ttl_s)) sig.push("--signal-ttl", String(c.signal.ttl_s))
					}
				}
			} catch (e) {
				process.stderr.write(\`claude-comm: the restart signal could not be loaded (\${(e && e.message) || e}); this start is being recorded as COLD.\\n\`)
			}
			// --pending-auto: what was already waiting in front of this session when it
			// opened, counted by the ledger itself so there is one implementation of it.
			// The covariate the ~/Dev/work leader's measurement asked for, and it is HIS
			// definition, not the inbox depth I proposed - his session #41 had an empty
			// mailbox and a 246-line report on disk, so mine would have scored the busiest
			// boot of his last five as EMPTY. Priced before adopting: 14 of 891 files, 17 ms
			// on his tree. FINDINGS.md#reboot-signal
			const rec = spawnSync(process.execPath, [led, "record", "start", "--agent", agent,
				"--source", p.source, "--session", basename(tp).replace(/\\.jsonl$/, ""),
				"--root", projectRoot, "--quiet", "--pending-auto", ...sig], { timeout: 5000, stdio: "ignore" })
			// A claim is destructive and a record is not retried. If the write failed after
			// the note was taken, that restart is gone and this line is the only thing that
			// will ever say so.
			if (sig.length && rec.status !== 0) {
				process.stderr.write(\`claude-comm: a restart signal for \${agent} was claimed but the ledger did not record it (exit \${rec.status}); that restart is now UNCOUNTED.\\n\`)
			}
		}
	} catch {}
} catch { /* an instrument must never break a session */ }

process.exit(delivered.status ?? 0)
`

/**
 * THE NOTICE, written into every project at `.comm/README.md`.
 *
 * An agent in a field project has hooks, a bus and a ledger, and until 2026-09-04 it had no
 * explanation of any of it anywhere in its own tree — the design lives in a DIFFERENT
 * repository it has no reason to open. So the first time it wondered what `.comm/` was, it
 * guessed. One of those guesses committed six files of live state to git.
 *
 * It is generated rather than copied, so the paths in it are THIS machine's real paths:
 * the update command names the actual checkout, and the feedback directory is one an agent
 * can write to without asking anyone where it is. It carries no timestamp and no counts,
 * because `--check` compares it byte for byte and a notice that drifted every day would
 * make that comparison worthless.
 */
const NOTICE = (here, root) => [
	"# claude-comm — what `.comm/` is, and the one thing you must not do",
	"",
	"This project talks to its other agents through a small message bus. You did not install it and you do",
	"not have to maintain it. Two facts are enough to work with it.",
	"",
	"**1. A message is only a doorbell; the file is the artifact.** `comm send` requires `--ref <file>` and",
	"has no `--body`: you point at a file in your own repo and the other agent reads it with its own tools.",
	"Content pasted into a message is refused by the receiving agent as a prompt injection, and it is right",
	"to refuse — it cannot tell a leader from an attacker.",
	"",
	"**2. Mail arrives at your TURN BOUNDARY, not immediately.** A hook drains your inbox when your turn",
	"ends, or when you next start. Nobody is interrupted mid-thought. If someone is idle, a doorbell can",
	"make them take a turn — it still never delivers anything itself.",
	"",
	"**3. The bus does not coordinate LOCAL RESOURCES — if you open one, say where.** Ports, sockets,",
	"containers, dev servers: nothing here sees them, and two agents in one tree will take the same one",
	"without either being told. Reported from `~/Dev/work` on 2026-09-04, and it is worth the line because",
	"of HOW it fails: three of that project's applications declared port `4173`, and two agents started in",
	"parallel would have killed each other's server while each read the result as *a broken test, not a",
	"port conflict* — so both would have searched in the wrong place, separately.",
	"",
	"```",
	"node .comm/bin/claim.mjs take port:4173 --purpose \"vite dev server\" [--pid <the server's pid>]",
	"node .comm/bin/claim.mjs list          who is holding what, and whose holder has died",
	"node .comm/bin/claim.mjs release port:4173",
	"```",
	"",
	"It **advises**: it opens nothing, kills nothing and blocks nothing — a mutex every agent can delete is a",
	"promise the filesystem does not make. What it buys is that a collision is one command away from being",
	"diagnosable instead of looking like a broken test, and your `SessionStart` says so without being asked.",
	"A claim whose holder has died reads as **a crash, not a stale lock** — nothing expires here.",
	"",
	"## Launching a SECOND session in the same folder — a reviewer, a helper",
	"",
	"**Identity here is where a session stands, not what you type.** A session in `db/` is `db`; nobody has to",
	"set `CLAUDE_COMM_AGENT`, and delivery never used it — it follows the hook stub's location.",
	"",
	"🔴 **So a second session started in the SAME folder is the same agent, and it will drain that agent's",
	"mail.** Measured: a turn ended by a second session in the leader's folder took the leader's waiting",
	"message (1 → 0); *the sender was still told it was delivered.* `comm who` says so when it happens.",
	"",
	"**Give it its own folder instead.** Add it to `.comm/config.json`, re-run the installer, start it there:",
	"",
	"```",
	"  \"agents\": { \"leader\": \".\", \"review\": \"review\" }",
	"```",
	"",
	"It then keeps its own inbox, is never mistaken for the leader, and can still write to the leader with",
	"`send` — nothing typed at launch. `CLAUDE_COMM_AGENT=` remains the only per-session answer when two",
	"sessions genuinely must share one directory. `CLAUDE_COMM_AGENT=none` is not that answer: an off-bus",
	"session receives nothing **and cannot send either**.",
	"",
	"## 🔴 Never commit `.comm/` — it is live state, not source",
	"",
	"`.comm/` holds inboxes, a delivery log, a lifecycle ledger and per-machine runtime notes. **It changes",
	"every turn.** Committing it puts another agent's mail in your history, makes branches conflict over a",
	"log nobody reads, and freezes a copy of the bus that then goes stale.",
	"",
	"The installer adds `.comm/` to your `.gitignore` — **but it runs once.** If you rewrite that file",
	"afterwards the rule disappears and nothing used to tell you. That happened here on 2026-09-04: a",
	"careful `.gitignore`, written against the things its author was thinking about, and `.comm/` was not",
	"one of them. Six files of live state were committed.",
	"",
	"So your `SessionStart` hook now asks, every session, whether anything under `.comm/` is *tracked* —",
	"not whether an ignore rule exists, because a rule can live in a parent `.gitignore`, in",
	"`.git/info/exclude`, or in a global `core.excludesFile`, and checking the rule would cry wolf in all",
	"three. If it warns you, this is the fix, and it keeps every file on disk:",
	"",
	"```",
	"git rm -r --cached .comm/",
	"echo '.comm/' >> .gitignore",
	"```",
	"",
	"## Using it",
	"",
	"```",
	"node .comm/bin/comm.mjs who                        who exists, who is running, who has mail waiting",
	"node .comm/bin/comm.mjs inbox                      what is waiting for you",
	"node .comm/bin/comm.mjs send <agent> --ref <file> [--note \"one line, no substance\"]",
	"```",
	"",
	"Every message must have this project's leader at one end — expert-to-expert is refused on purpose, so",
	"that no coordination happens off the board. Refs resolve **for the reader**: give the path as *you*",
	"see it and the bus rewrites it for them.",
	"",
	"## Installing and updating",
	"",
	"```",
	`node ${join(here, "install.mjs")} ${root}              install or update — safe to re-run, idempotent`,
	`node ${join(here, "install.mjs")} ${root} --check      is anything out of date?`,
	"```",
	"",
	"A running agent picks up a new bus at its next turn boundary, because the hook re-executes it every",
	"time. Changed hooks and settings take effect at that agent's next session.",
	"",
	"## Something wrong with it? Write to the agent who maintains it",
	"",
	"Drop a Markdown file into:",
	"",
	"```",
	`${join(here, "exchange", "field", "in")}`,
	"```",
	"",
	"Name it `<project>-<you>-<date>-<topic>.md`. **That is the whole protocol** — the file is the",
	"artifact, there is no form and no command to learn. Its maintainer's own boot reports an unanswered",
	"channel at every one of his session starts, so it will be seen; the reply comes back as a file beside",
	"it in `out/`.",
	"",
	"Two things make a report useful here, and they are the standard this tool is held to:",
	"",
	"- **Say what you did NOT check.** Its absence is read as a defect in the report, not a clean bill.",
	"- **A measurement beats an opinion.** \"It did X, I expected Y, here is the command\" is worth more",
	"  than a polished analysis. If you cannot say what would have made the check fail, it did not check.",
	"",
	"Bugs, missing features, a guard that fired when nothing was wrong, wording that misled you — all of",
	"it is wanted. A guard that is defensible every time it is bypassed is already failing.",
	"",
	"## The real documentation, if you want it",
	"",
	`${"`" + join(here, "README.md") + "`"} is the design and \`FINDINGS.md\` beside it is why every guard exists. You need neither to`,
	"use the bus.",
	"",
].join("\n")

/**
 * ABSENT and UNPARSEABLE are not the same thing, and conflating them is data
 * loss. `readJson(sPath, {})` treated a settings.json it could not parse as an
 * empty one, so `withHooks` merged into `{}` and the write replaced the user's
 * file with nothing but comm's two hooks — permissions, env and unrelated hooks
 * gone, output `✓ installed`, exit 0. A trailing comma does it; so does a merge
 * conflict, which is unparseable by construction and likeliest in exactly the
 * multi-repo projects this tool targets. Measured, not theorised, and it had
 * already run against 7 agents.
 *
 * A file we cannot read is a file we must not overwrite.
 */
function readJson(p, fallback) {
	if (!existsSync(p)) return fallback
	const raw = readFileSync(p, "utf8")
	try { return JSON.parse(raw) } catch (e) {
		throw new Error(
			`${p} exists but is not valid JSON (${e.message}).\n` +
			`  Refusing to touch it: merging into a fallback would have silently replaced your\n` +
			`  settings with only claude-comm's hooks. Fix the JSON, then re-run.`
		)
	}
}

/**
 * The hook command, and why it is not just `node ... comm-hook.mjs`.
 *
 * `FINDINGS.md#hookless-launch`: a session launched outside an interactive shell -
 * `kitten @ launch`, a `.desktop` file, cron - inherits a PATH with no nvm on it, so
 * `node` is not found, EVERY hook dies, and the session runs normally with no bus, no
 * mail delivered at any turn boundary, and nothing saying so. A self-launched expert is
 * launched by a program, never by a person's shell, so this is the shape that would have
 * made the whole autonomy program measure nothing.
 *
 * The guard does not make a node-less session work. It makes one impossible to mistake
 * for a working one, and only at `SessionStart` - a warning printed at every turn
 * boundary is a warning nobody reads, so `Stop` stays silent and relies on the one the
 * session was given when it started.
 *
 * It still exits 0 on every path: a broken bus must never break a session.
 */
const hookCommand = (verb) => {
	const run = `node "$CLAUDE_PROJECT_DIR/.claude/comm-hook.mjs" ${verb}`
	if (verb !== "session-start") return `if command -v node >/dev/null 2>&1; then ${run}; fi`
	return `if command -v node >/dev/null 2>&1; then ${run}; else ` +
		`echo "claude-comm: node is NOT on this session PATH, so the bus hooks did not run. ` +
		`No mail will be delivered at any turn boundary and nothing else will say so. ` +
		`This session was launched outside an interactive shell (kitten @ launch, a .desktop file, cron); ` +
		`relaunch it through a login shell."; fi`
}

/** Merge our two hooks into a settings object without disturbing anything else. */
function withHooks(settings) {
	const s = { ...settings }
	s.hooks = { ...(s.hooks || {}) }
	for (const [event, verb] of [["Stop", "stop"], ["SessionStart", "session-start"]]) {
		const keep = (s.hooks[event] || []).filter(
			(g) => !(g.hooks || []).some((h) => String(h.command || "").includes("comm-hook"))
		)
		s.hooks[event] = [
			...keep,
			{ hooks: [{ type: "command", command: hookCommand(verb) }] },
		]
	}
	return s
}

function write(path, content, results) {
	const cur = existsSync(path) ? readFileSync(path, "utf8") : null
	if (cur === content) { results.ok.push(path); return }
	if (CHECK) { results.drift.push(path); return }
	mkdirSync(dirname(path), { recursive: true })
	// WRITE THEN RENAME, never truncate-then-write. An upgrade is applied to a
	// project whose agents are LIVE — that is the normal case, not an edge one —
	// and `.comm/bin/comm.mjs` is executed by a Stop hook at every turn boundary.
	// A truncating write leaves a window in which the hook loads a partial file,
	// fails to parse, and that turn's delivery is silently missed. rename(2) is
	// atomic within a filesystem, so a reader sees either the whole old file or
	// the whole new one. Same directory, so it never crosses a filesystem.
	const tmp = `${path}.tmp-${randomBytes(4).toString("hex")}`
	try {
		writeFileSync(tmp, content)
		renameSync(tmp, path)
	} catch (e) {
		try { unlinkSync(tmp) } catch {}
		throw e
	}
	results.wrote.push(path)
}

// ── 1. the bus itself ───────────────────────────────────────────────────────
const commDir = join(ROOT, ".comm")
const cfgPath = join(commDir, "config.json")
if (!existsSync(cfgPath)) {
	console.error(`✗ no .comm/config.json at ${ROOT}\n  run:  cd ${ROOT} && node ${join(HERE, "bin/comm.mjs")} init`)
	process.exit(1)
}
const cfg = readJson(cfgPath)
const results = { wrote: [], ok: [], drift: [], failed: [], missing: [] }

if (!CHECK) mkdirSync(join(commDir, "bin"), { recursive: true })
const busSrc = readFileSync(join(HERE, "bin", "comm.mjs"), "utf8")
write(join(commDir, "bin", "comm.mjs"), busSrc, results)
// The two instruments travel WITH the bus rather than being reached by an absolute
// path into this checkout. An absolute path breaks every field hook the day the
// checkout moves, and breaks it silently — hooks exit 0 by design. A copy can go
// stale instead, which is a failure this project already detects: `field:*` compares
// the installed files against this repo's and reddens on any difference.
// `claim.mjs` travels because the collision it makes diagnosable happens in FIELD projects,
// between two agents in one tree - a copy that lived only in claude-comm would have been
// present at none of it. It imports `session-registry.mjs`, which is already on this list
// and must stay above it for that reason.
for (const f of ["session-registry.mjs", "ledger.mjs", "wake.mjs", "restart-signal.mjs", "claim.mjs"]) {
	write(join(commDir, "bin", f), readFileSync(join(HERE, "bin", f), "utf8"), results)
}

// The notice, and the channel it points at. A feedback path an agent cannot find is a
// feedback path that does not exist, so the directory is CREATED here rather than
// documented and hoped for - a notice naming a directory nobody made is a dangling
// pointer, which this project holds to be worse than no pointer at all (A27/A28).
write(join(commDir, "README.md"), NOTICE(HERE, ROOT) + "\n", results)
if (!CHECK) { try { mkdirSync(join(HERE, "exchange", "field", "in"), { recursive: true })
	mkdirSync(join(HERE, "exchange", "field", "out"), { recursive: true }) } catch {} }

// ── 2. per-agent stub + hooks ───────────────────────────────────────────────
for (const [id, relPath] of Object.entries(cfg.agents)) {
	const agentRoot = resolve(ROOT, relPath)
	// A roster entry with no directory used to `continue` with a stderr warning and
	// contribute nothing to `results`, so `--check` printed "✓ N file(s) in sync
	// across 3 agents" and exited 0 while an agent was entirely uninstalled. That
	// count was of the ROSTER, not of what was installed. This is the pre-flight the
	// operator trusts before a swap; a green line that overstates its own coverage is
	// the exact failure this project exists to catch.
	if (!existsSync(agentRoot)) { results.missing.push(`${id} → ${agentRoot}`); continue }

	write(join(agentRoot, ".claude", "comm-hook.mjs"), STUB, results)

	// One unreadable agent must not abort the other six, and must not be
	// reported as installed either.
	const sPath = join(agentRoot, ".claude", "settings.json")
	try {
		const merged = withHooks(readJson(sPath, {}))
		write(sPath, JSON.stringify(merged, null, 2) + "\n", results)
	} catch (e) {
		console.error(`  ✗ ${id}: ${e.message}`)
		results.failed.push(sPath)
		continue
	}

	if (!CHECK) mkdirSync(join(commDir, "inbox", id), { recursive: true })
}

// ── 3. keep live state out of git ───────────────────────────────────────────
// The README promises this unconditionally. Guarding the whole block on
// `existsSync` meant a project WITHOUT a .gitignore silently got no ignore rule
// at all, while `--check` still reported everything in sync — so live inboxes
// and log.jsonl became committable in exactly the fresh projects most likely to
// be `git init`-ed right after install.
const giPath = join(ROOT, ".gitignore")
const gi = existsSync(giPath) ? readFileSync(giPath, "utf8") : ""
if (!/^\.comm\/?$/m.test(gi)) {
	if (CHECK) results.drift.push(giPath)
	else {
		writeFileSync(giPath, (gi ? gi.replace(/\n*$/, "\n") + "\n" : "") + "# claude-comm live state (regenerate with install.mjs)\n.comm/\n")
		results.wrote.push(giPath)
	}
} else results.ok.push(giPath)

// ── report ──────────────────────────────────────────────────────────────────
// A partial install must not exit 0. The whole point of the readJson fix is
// that the operator learns a file was skipped; a green summary would bury it.
if (results.missing.length) {
	console.error(`\n✗ claude-comm: ${results.missing.length} roster agent(s) have NO directory — nothing was installed for them:`)
	for (const m of results.missing) console.error(`    ${m}`)
	console.error(`  Fix .comm/config.json (or create the directory) and re-run. Mail addressed to them would queue forever.`)
	process.exit(1)
}
if (results.failed.length) {
	console.error(`\n✗ claude-comm: ${results.failed.length} agent(s) SKIPPED — their settings.json could not be parsed and were left untouched:`)
	for (const p of results.failed) console.error(`    ${p.replace(ROOT + "/", "")}`)
	console.error(`  Every other agent was installed. Fix the JSON above and re-run.`)
	process.exit(1)
}
// The same question the SessionStart guard asks, asked once more at the moment an operator
// is actually looking at this tool. Cheap, and it is the only point in the lifecycle where
// somebody is holding the thing that can fix it.
try {
	// Same walk as the stub's, and for the same finding (review #6 F7). Two copies rather
	// than one helper, deliberately: the stub is a GENERATED string that cannot import from
	// this file, so a shared helper here would be a rule enforced in one of the two places
	// that need it - which is how the installed bus went stale twice before.
	let gitRoot = null
	for (let d = ROOT; ;) {
		if (existsSync(join(d, ".git"))) { gitRoot = d; break }
		const up = dirname(d)
		if (up === d) break
		d = up
	}
	if (gitRoot) {
		const g = spawnSync("git", ["ls-files", "--", ".comm"], { cwd: ROOT, encoding: "utf8", timeout: 5000 })
		const tracked = String(g.stdout || "").split("\n").filter(Boolean)
		if (tracked.length) {
			console.error(`\n⚠ claude-comm: ${tracked.length} file(s) of LIVE BUS STATE are committed to this project's git:`)
			for (const t of tracked.slice(0, 6)) console.error(`    ${t}`)
			if (tracked.length > 6) console.error(`    … and ${tracked.length - 6} more`)
			console.error(`  .comm/ changes every turn and is per-machine. Fix, keeping every file on disk:`)
			console.error(`    git rm -r --cached .comm/   &&   echo '.comm/' >> .gitignore`)
		}
	}
} catch {}

if (CHECK) {
	if (results.drift.length) {
		// A MACHINE-READABLE LIST, on its own marked line, because a reader that scrapes the
		// human prose is a reader that reports whatever else happens to be shaped like it.
		// Review #6 F3: boot.mjs's field row took "any line indented four spaces, on either
		// stream" as a drifted filename, and the git-tracking warning above prints its file
		// list, its "… and N more" line AND its fix command at that indent. Measured: nine
		// names for one drifted file, five bus files listed as DRIFT beside "bus current
		// (5 files)" in the same sentence, and `git rm -r --cached .comm/ && echo …` rendered
		// as a filename. The row it replaced said only "HOOK DRIFT" - vague; this was
		// confidently wrong, which is worse, and it is this repo's signature defect: a row
		// that names something other than what it measured.
		//
		// Emitted BEFORE the prose and on stdout, so the two never share a channel or a
		// shape. The prose stays exactly as it was: an operator reads it, and this line is
		// for the one reader that is a program.
		console.log(`claude-comm-drift: ${JSON.stringify(results.drift.map((p) => p.replace(ROOT + "/", "")))}`)
		console.error(`✗ claude-comm: ${results.drift.length} file(s) out of date:`)
		for (const p of results.drift) console.error(`    ${p.replace(ROOT + "/", "")}`)
		console.error(`\n  fix:  node ${join(HERE, "install.mjs")} ${ROOT}`)
		process.exit(1)
	}
	console.log(`✓ claude-comm: ${results.ok.length} file(s) in sync across ${Object.keys(cfg.agents).length} agents`)
} else {
	console.log(`✓ claude-comm installed at ${ROOT}`)
	console.log(`  agents:  ${Object.keys(cfg.agents).join(", ")}`)
	console.log(`  wrote:   ${results.wrote.length} file(s)${results.ok.length ? `  (${results.ok.length} already current)` : ""}`)
	// This line used to stop at "NEXT session", which is true of settings.json and
	// FALSE of the bus — the file an upgrade actually changes. The stub spawns
	// `node <bus> hook …` fresh on every fire, so a replaced bus is live at the
	// running agent's very next turn end, with no restart. Measured on a scratch
	// bus. An operator who believed the swap was deferred would be wrong about the
	// one part of it that is not.
	console.log(`\n  settings.json + hook stubs take effect in each agent's NEXT session —`)
	console.log(`  a running one has already loaded its settings.`)
	console.log(`  .comm/bin/comm.mjs is NOT deferred: the stub re-executes it on every hook`)
	console.log(`  fire, so a running agent picks up this bus at its next turn end.`)
}
