#!/usr/bin/env node
/**
 * claude-comm installer — wires the bus into a hub-and-spoke project.
 *
 *   node install.mjs <project-root> [--check]
 *
 * It is IDEMPOTENT and NON-DESTRUCTIVE: existing `.claude/settings.json` keys and
 * unrelated hooks are preserved; only a hook whose command mentions `comm-hook`
 * is replaced. `--check` reports drift without writing (so it can be a gate).
 *
 * Path strategy, measured rather than assumed: Claude Code runs hooks with both
 * cwd and $CLAUDE_PROJECT_DIR set to the repo root. We still resolve the bus from
 * the STUB's own location (import.meta.url), so nothing breaks if the project is
 * moved, cloned, or a hook is invoked from a subdirectory.
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync, copyFileSync, renameSync, unlinkSync } from "node:fs"
import { join, dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { randomBytes } from "node:crypto"

const HERE = dirname(fileURLToPath(import.meta.url))
const CHECK = process.argv.includes("--check")
const ROOT = resolve(process.argv[2] || process.cwd())

const STUB = `#!/usr/bin/env node
// GENERATED by claude-comm install.mjs — do not edit.
// Resolves the bus from THIS FILE's location, then forwards the hook payload.
import { existsSync } from "node:fs"
import { join, dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { spawnSync } from "node:child_process"

let dir = resolve(dirname(fileURLToPath(import.meta.url)))
// This stub lives at <agentRoot>/.claude/comm-hook.mjs, one per agent, so its own
// location IS this agent's identity. The hook payload's cwd is NOT: it follows the
// Bash tool's working directory, so a leader that cds into an expert's repo during
// a turn would otherwise be identified as that expert and drain its inbox.
const agentRoot = dirname(dir)
let bus = null
for (;;) {
\tconst c = join(dir, ".comm", "bin", "comm.mjs")
\tif (existsSync(c)) { bus = c; break }
\tconst up = dirname(dir)
\tif (up === dir) break
\tdir = up
}
// A missing bus must never break the session.
if (!bus) process.exit(0)
const r = spawnSync(process.execPath, [bus, "hook", ...process.argv.slice(2), "--agent-root", agentRoot], { stdio: "inherit" })
process.exit(r.status ?? 0)
`

/**
 * ABSENT and UNPARSEABLE are not the same thing, and conflating them is data
 * loss. `readJson(sPath, {})` treated a settings.json it could not parse as an
 * empty one, so `withHooks` merged into `{}` and the write replaced the user's
 * file with nothing but comm's two hooks — permissions, env and unrelated hooks
 * gone, output `✓ installed`, exit 0. A trailing comma does it; so does a merge
 * conflict, which is unparseable by construction and likeliest in exactly the
 * multi-repo projects this tool targets. Measured, not theorised, and it had
 * already run against 7 agents.
 *
 * A file we cannot read is a file we must not overwrite.
 */
function readJson(p, fallback) {
	if (!existsSync(p)) return fallback
	const raw = readFileSync(p, "utf8")
	try { return JSON.parse(raw) } catch (e) {
		throw new Error(
			`${p} exists but is not valid JSON (${e.message}).\n` +
			`  Refusing to touch it: merging into a fallback would have silently replaced your\n` +
			`  settings with only claude-comm's hooks. Fix the JSON, then re-run.`
		)
	}
}

/** Merge our two hooks into a settings object without disturbing anything else. */
function withHooks(settings) {
	const s = { ...settings }
	s.hooks = { ...(s.hooks || {}) }
	for (const [event, verb] of [["Stop", "stop"], ["SessionStart", "session-start"]]) {
		const keep = (s.hooks[event] || []).filter(
			(g) => !(g.hooks || []).some((h) => String(h.command || "").includes("comm-hook"))
		)
		s.hooks[event] = [
			...keep,
			{ hooks: [{ type: "command", command: `node "$CLAUDE_PROJECT_DIR/.claude/comm-hook.mjs" ${verb}` }] },
		]
	}
	return s
}

function write(path, content, results) {
	const cur = existsSync(path) ? readFileSync(path, "utf8") : null
	if (cur === content) { results.ok.push(path); return }
	if (CHECK) { results.drift.push(path); return }
	mkdirSync(dirname(path), { recursive: true })
	// WRITE THEN RENAME, never truncate-then-write. An upgrade is applied to a
	// project whose agents are LIVE — that is the normal case, not an edge one —
	// and `.comm/bin/comm.mjs` is executed by a Stop hook at every turn boundary.
	// A truncating write leaves a window in which the hook loads a partial file,
	// fails to parse, and that turn's delivery is silently missed. rename(2) is
	// atomic within a filesystem, so a reader sees either the whole old file or
	// the whole new one. Same directory, so it never crosses a filesystem.
	const tmp = `${path}.tmp-${randomBytes(4).toString("hex")}`
	try {
		writeFileSync(tmp, content)
		renameSync(tmp, path)
	} catch (e) {
		try { unlinkSync(tmp) } catch {}
		throw e
	}
	results.wrote.push(path)
}

// ── 1. the bus itself ───────────────────────────────────────────────────────
const commDir = join(ROOT, ".comm")
const cfgPath = join(commDir, "config.json")
if (!existsSync(cfgPath)) {
	console.error(`✗ no .comm/config.json at ${ROOT}\n  run:  cd ${ROOT} && node ${join(HERE, "bin/comm.mjs")} init`)
	process.exit(1)
}
const cfg = readJson(cfgPath)
const results = { wrote: [], ok: [], drift: [], failed: [], missing: [] }

if (!CHECK) mkdirSync(join(commDir, "bin"), { recursive: true })
const busSrc = readFileSync(join(HERE, "bin", "comm.mjs"), "utf8")
write(join(commDir, "bin", "comm.mjs"), busSrc, results)

// ── 2. per-agent stub + hooks ───────────────────────────────────────────────
for (const [id, relPath] of Object.entries(cfg.agents)) {
	const agentRoot = resolve(ROOT, relPath)
	// A roster entry with no directory used to `continue` with a stderr warning and
	// contribute nothing to `results`, so `--check` printed "✓ N file(s) in sync
	// across 3 agents" and exited 0 while an agent was entirely uninstalled. That
	// count was of the ROSTER, not of what was installed. This is the pre-flight the
	// operator trusts before a swap; a green line that overstates its own coverage is
	// the exact failure this project exists to catch.
	if (!existsSync(agentRoot)) { results.missing.push(`${id} → ${agentRoot}`); continue }

	write(join(agentRoot, ".claude", "comm-hook.mjs"), STUB, results)

	// One unreadable agent must not abort the other six, and must not be
	// reported as installed either.
	const sPath = join(agentRoot, ".claude", "settings.json")
	try {
		const merged = withHooks(readJson(sPath, {}))
		write(sPath, JSON.stringify(merged, null, 2) + "\n", results)
	} catch (e) {
		console.error(`  ✗ ${id}: ${e.message}`)
		results.failed.push(sPath)
		continue
	}

	if (!CHECK) mkdirSync(join(commDir, "inbox", id), { recursive: true })
}

// ── 3. keep live state out of git ───────────────────────────────────────────
// The README promises this unconditionally. Guarding the whole block on
// `existsSync` meant a project WITHOUT a .gitignore silently got no ignore rule
// at all, while `--check` still reported everything in sync — so live inboxes
// and log.jsonl became committable in exactly the fresh projects most likely to
// be `git init`-ed right after install.
const giPath = join(ROOT, ".gitignore")
const gi = existsSync(giPath) ? readFileSync(giPath, "utf8") : ""
if (!/^\.comm\/?$/m.test(gi)) {
	if (CHECK) results.drift.push(giPath)
	else {
		writeFileSync(giPath, (gi ? gi.replace(/\n*$/, "\n") + "\n" : "") + "# claude-comm live state (regenerate with install.mjs)\n.comm/\n")
		results.wrote.push(giPath)
	}
} else results.ok.push(giPath)

// ── report ──────────────────────────────────────────────────────────────────
// A partial install must not exit 0. The whole point of the readJson fix is
// that the operator learns a file was skipped; a green summary would bury it.
if (results.missing.length) {
	console.error(`\n✗ claude-comm: ${results.missing.length} roster agent(s) have NO directory — nothing was installed for them:`)
	for (const m of results.missing) console.error(`    ${m}`)
	console.error(`  Fix .comm/config.json (or create the directory) and re-run. Mail addressed to them would queue forever.`)
	process.exit(1)
}
if (results.failed.length) {
	console.error(`\n✗ claude-comm: ${results.failed.length} agent(s) SKIPPED — their settings.json could not be parsed and were left untouched:`)
	for (const p of results.failed) console.error(`    ${p.replace(ROOT + "/", "")}`)
	console.error(`  Every other agent was installed. Fix the JSON above and re-run.`)
	process.exit(1)
}
if (CHECK) {
	if (results.drift.length) {
		console.error(`✗ claude-comm: ${results.drift.length} file(s) out of date:`)
		for (const p of results.drift) console.error(`    ${p.replace(ROOT + "/", "")}`)
		console.error(`\n  fix:  node ${join(HERE, "install.mjs")} ${ROOT}`)
		process.exit(1)
	}
	console.log(`✓ claude-comm: ${results.ok.length} file(s) in sync across ${Object.keys(cfg.agents).length} agents`)
} else {
	console.log(`✓ claude-comm installed at ${ROOT}`)
	console.log(`  agents:  ${Object.keys(cfg.agents).join(", ")}`)
	console.log(`  wrote:   ${results.wrote.length} file(s)${results.ok.length ? `  (${results.ok.length} already current)` : ""}`)
	// This line used to stop at "NEXT session", which is true of settings.json and
	// FALSE of the bus — the file an upgrade actually changes. The stub spawns
	// `node <bus> hook …` fresh on every fire, so a replaced bus is live at the
	// running agent's very next turn end, with no restart. Measured on a scratch
	// bus. An operator who believed the swap was deferred would be wrong about the
	// one part of it that is not.
	console.log(`\n  settings.json + hook stubs take effect in each agent's NEXT session —`)
	console.log(`  a running one has already loaded its settings.`)
	console.log(`  .comm/bin/comm.mjs is NOT deferred: the stub re-executes it on every hook`)
	console.log(`  fire, so a running agent picks up this bus at its next turn end.`)
}
