#!/usr/bin/env node
// GENERATED by claude-comm install.mjs — do not edit.
// Resolves the bus from THIS FILE's location, then forwards the hook payload.
import { existsSync, readFileSync, readdirSync, readlinkSync, writeFileSync } from "node:fs"
import { join, dirname, resolve, basename, relative } from "node:path"
import { fileURLToPath, pathToFileURL } from "node:url"
import { spawnSync } from "node:child_process"

let dir = resolve(dirname(fileURLToPath(import.meta.url)))
// This stub lives at <agentRoot>/.claude/comm-hook.mjs, one per agent, so its own
// location IS this agent's identity. The hook payload's cwd is NOT: it follows the
// Bash tool's working directory, so a leader that cds into an expert's repo during
// a turn would otherwise be identified as that expert and drain its inbox.
const agentRoot = dirname(dir)

/**
 * THE SESSION THIS HOOK RECORDS MUST BE A SESSION IN THIS PROJECT.
 *
 * `sessionPid()` walks to the nearest `claude` ancestor, which is right when the hook is
 * fired BY that session and wrong the moment anything else fires it - a test suite, an
 * operator reproducing a bug, an agent running another project's stub by hand. Then the
 * walk reaches the CALLER's session and this hook writes that session's registry entry to
 * point at a transcript from somewhere else. Measured five times on 2026-09-04, most
 * recently as `pid 820277 -> fake.jsonl (stop)` in the operator's own boot report, green.
 *
 * The invariant is small and exact: I am a hook belonging to a project, so the session I
 * resolve must be running inside that project. When it is not, something is firing me on
 * behalf of a session I do not speak for, and the only safe act is to record nothing.
 */
const ownsSession = (pid) => {
	try {
		const cwd = readlinkSync(`/proc/${pid}/cwd`)
		return cwd === projectRoot || cwd.startsWith(projectRoot + "/")
	} catch { return false }
}
let bus = null, projectRoot = null
for (;;) {
	const c = join(dir, ".comm", "bin", "comm.mjs")
	if (existsSync(c)) { bus = c; projectRoot = dir; break }
	const up = dirname(dir)
	if (up === dir) break
	dir = up
}
// A missing bus must never break the session.
if (!bus) process.exit(0)

const forward = (input, notices = []) => spawnSync(process.execPath,
	// --agent-root BEFORE any notice: the bus takes the FIRST one, so no notice text can stand in for it.
	[bus, "hook", ...process.argv.slice(2), "--agent-root", agentRoot, ...notices.flatMap((n) => ["--notice", n])],
	input === null ? { stdio: "inherit" } : { input, stdio: ["pipe", "inherit", "inherit"] })

// STOP. Delivery is unchanged in substance - same bus, same arguments - but the payload
// is now read here rather than inherited, because the registry needs a SECOND WITNESS.
//
// G2 (review #5): a SessionStart that never REACHED record() - module missing, module
// unloadable, runtime dir unwritable, hook killed during delivery - leaves the previous
// entry standing, and after a /clear that entry names a session that has ended. Nothing
// in the entry can reveal it: pid, boot id and start tick all still match, it is the same
// process. `Stop` is the only thing on this machine that is handed the LIVE transcript at
// every turn boundary, so it is the only thing that can heal those paths - and it heals
// them within one turn instead of never.
//
// The ledger is deliberately NOT here: it records STARTS, and a start is not a turn
// boundary. The registry work is a lookup and a string compare, and it writes only when
// the transcript actually differs - once per session, plus once after a clear.
if (process.argv[2] !== "session-start") {
	let stopRaw = ""
	try { stopRaw = readFileSync(0, "utf8") } catch {}
	const stopped = forward(stopRaw)
	try {
		const reg = join(dirname(bus), "session-registry.mjs")
		if (existsSync(reg)) {
			const sp = JSON.parse(stopRaw || "{}")
			if (typeof sp.transcript_path === "string" && sp.transcript_path) {
				const m = await import(pathToFileURL(reg).href)
				const who = m.sessionPid()
				const r = ownsSession(who)
					? m.refresh({ pid: who, transcript: sp.transcript_path, agent: null, source: "stop" })
					: { ok: true, unchanged: true }
				// Silent on the common path. A turn boundary that printed a line every time
				// would be a warning nobody reads; this speaks only when it CHANGED something
				// and the change failed, which is the state that matters.
				if (!r.ok && !r.unchanged) process.stderr.write(`claude-comm: could not refresh the session registry (${r.why}).\n`)
			}
		}
	} catch { /* an instrument must never break a turn boundary */ }
	// THE DOORBELL. Mail lands at the recipient's TURN BOUNDARY, so an agent that is alive
	// but idle never receives it - measured over 26 real deliveries as a leader->expert
	// median of 1462 s. Nothing here delivers anything: it makes an idle session take a
	// turn, and that turn's own Stop hook runs the delivery that is already gated.
	//
	// Cheap first, always: a readdir of the inboxes. wake.mjs is only spawned when
	// something is actually waiting for somebody else, so the common turn boundary pays
	// one directory listing and nothing more. It never affects this turn's exit code.
	try {
		const wake = join(dirname(bus), "wake.mjs")
		const ibx = join(projectRoot, ".comm", "inbox")
		let waiting = false
		for (const a of readdirSync(ibx)) {
			try { if (readdirSync(join(ibx, a)).some((f) => f.endsWith(".json"))) { waiting = true; break } } catch {}
		}
		if (waiting && existsSync(wake)) {
			spawnSync(process.execPath, [wake, "--root", projectRoot], { timeout: 10000, stdio: "ignore" })
		}
	} catch { /* a doorbell must never break a turn boundary */ }
	// Same rule as the session-start exit at the foot of this file, and I fixed that one
	// first while assuming it was the only one — it is not. THE STOP PATH IS THE HOT ONE:
	// it runs at every turn boundary, so a bus that cannot start breaks every turn until
	// somebody notices. The bus exits 0 on every hook decision (the block travels as stdout
	// JSON), so a non-zero here means it never RAN.
	if (stopped.status) {
		process.stderr.write(`claude-comm: the bus could not RUN (exit ${stopped.status}) — the hook path exits 0 on every decision, so this is a broken or half-installed bus, not a verdict. Your mail is untouched and this turn is not blocked. Re-run the installer.\n`)
	}
	process.exit(0)
}

// SESSION-START. The payload can be read only ONCE and the bus is no longer its only
// consumer, so this stub reads it and hands the bytes on.
let raw = ""
try { raw = readFileSync(0, "utf8") } catch {}

// WHAT THE AGENT MUST BE TOLD GOES TO THE BUS, NEVER TO STDERR (2026-09-19). Claude Code files a
// SessionStart hook's stderr in the transcript and never in the model's context: the bus's own
// introduction went there, said once, and 2 of ~180 field transcripts carry it, both with an
// empty content - no agent ever read it. So what an agent can act on is gathered HERE, before
// delivery, and handed to the bus, whose one JSON is what the model reads. A marker that says a
// notice was given is written only once the bus that shows it has run. FINDINGS.md#unseen-introduction
const notices = [], marks = []

// THE BUS INTRODUCES ITSELF AT EVERY START, IN THE ONE CHANNEL A MODEL READS. Its only introduction was a
// stderr line said once, and every agent that used this bus learned it from a person. Every start, because
// every start is a new reader; four lines, because it is paid on every boot. The commands are written to
// run from THIS agent's folder: .comm/bin/comm.mjs does not exist in an expert's subdirectory. The name
// is asked of the bus - the one place identity is resolved - and reused by the ledger below.
let whoIs = ""
try {
	const w = spawnSync(process.execPath, [bus, "whoami", "--agent-root", agentRoot],
		{ cwd: agentRoot, encoding: "utf8", timeout: 5000 })
	if (w.status === 0) whoIs = String(w.stdout).trim()
} catch {}
try {
	const cf = JSON.parse(readFileSync(join(projectRoot, ".comm", "config.json"), "utf8"))
	const agents = (cf && cf.agents) || {}, lead = cf && cf.leader
	if (whoIs && Object.prototype.hasOwnProperty.call(agents, whoIs)) {
		const cmd = "node " + relative(agentRoot, join(projectRoot, ".comm", "bin", "comm.mjs"))
		const others = Object.keys(agents).filter((a) => a !== whoIs && a !== lead)
		const names = others.slice(0, 12).join(", ") + (others.length > 12 ? ", +" + (others.length - 12) : "")
		const role = whoIs === lead
			? "the LEADER of this project's message bus - " + (others.length ? "experts: " + names : "no expert on the roster yet") +
				". Experts write only to you: you are the bridge between them, and the one who answers the owner."
			: "an EXPERT on this project's message bus. Your leader is '" + lead + "': you write to it, never to another expert."
		notices.push([
			"[claude-comm] You are '" + whoIs + "', " + role,
			"A message is a doorbell that points at a FILE: " + cmd + " send " + (whoIs === lead ? "<agent>" : lead) +
				' --ref <file> --note "<where to read, then what is decided>". It reaches the other session at its turn boundary.',
			"How to work with it - replying, launching an expert, restarting, the rules: the claude-comm skill, or " +
				relative(agentRoot, join(projectRoot, ".comm", "README.md")) + ".",
			"Your mail: " + cmd + " inbox",
		].join("\n"))
	}
} catch { /* an introduction must never cost a delivery */ }
	// IS THE LIVE BUS STATE IN THIS PROJECT'S GIT? Measured 2026-09-04: the ~/Dev/work
	// leader put his repo under git and wrote a careful .gitignore — against the things he
	// was thinking about. In his own words, *".comm/ did not exist in my head as a category,
	// so it did not exist in the file"*, and six files of live state were committed: the
	// delivery log, four delivered messages, his config. Nothing told him. install.mjs
	// appends the ignore rule, but it runs ONCE and a .gitignore rewritten afterwards
	// silently undoes it — which is exactly what happened.
	//
	// So this asks the only question with no false positive: are files under .comm/ TRACKED?
	// Not "is there an ignore rule" — a rule can live in a parent .gitignore, in
	// .git/info/exclude, or in a global core.excludesFile, and a check on the rule would cry
	// wolf in every one of those. Tracked-or-not is the defect itself.
	//
	// WHERE the repository is — not whether one begins exactly here. Review #6 F7: this
	// asked `existsSync(join(projectRoot, ".git"))`, which is the one question git never
	// asks: `git ls-files` walks UP. Demonstrated by the reviewer — a repo at repo/ with the
	// bus installed at repo/sub/, seven files of live state tracked, and this guard silent.
	// The comment above claimed "the only question with no false positive". That was true,
	// and it had a false NEGATIVE it did not name, in the configuration a field project is
	// most likely to be in: a bus living inside a larger repository.
	//
	// WALKED, not spawned. The point of the old existsSync was that a project outside git
	// pays no process at session start, and `git rev-parse` would cost one in every project
	// on every start, repository or not. The walk buys the correct answer at the old price.
	let gitRoot = null
	try {
		let d = projectRoot
		for (;;) {
			if (existsSync(join(d, ".git"))) { gitRoot = d; break }
			const up = dirname(d)
			if (up === d) break
			d = up
		}
	} catch { gitRoot = null }
	try {
		if (gitRoot) {
			const g = spawnSync("git", ["ls-files", "--", ".comm"],
				{ cwd: projectRoot, encoding: "utf8", timeout: 5000 })
			// The separator below is written with a DOUBLED backslash on purpose. This string is
			// built inside install.mjs's STUB template literal, so a single-backslash escape is
			// resolved when the stub is WRITTEN, not when it runs — a newline escape becomes a
			// real line break inside a string literal, and a string literal with a line break in
			// it does not parse. Measured while adding this guard: the generated hook became a
			// SyntaxError, so EVERY hook path in every project exited 1 — the bus dead in exactly
			// the way its first rule forbids — and the suite reported it as "A5 corrupt config is
			// inert", a case about something else entirely. Same trap for any escape added here.
			// 🔴 THE PROBE'S SILENCE IS NOT EVIDENCE (review #7 F7). `g.status` was never read,
			// and every way this probe can fail — a locked .git/index (exit 128), git absent
			// from PATH (spawn error, stdout null), a safe.directory refusal on a repo owned by
			// another user, a corrupt object store, the 5 s timeout — produces an EMPTY stdout,
			// which is byte-identical to the clean answer. Measured on a repository with 8 files
			// of live bus state genuinely committed: chmod 000 .git/index, and the guard whose
			// comment called it "the only question with no false positive" went silent. Two rows
			// away in bin/boot.mjs the same distinction is drawn correctly, between
			// "install --check refused (exit N)" and a parsed list.
			if (g.status !== 0 || g.error) {
				notices.push(
					`claude-comm: git could not be asked whether .comm/ is committed here ` +
					`(${g.error ? String(g.error.message || g.error) : `git ls-files exited ${g.status}`}). ` +
					`This is NOT the same as "nothing is committed" - the question is unanswered.`)
			}
			const tracked = String(g.stdout || "").split("\n").filter(Boolean)
			if (tracked.length) {
				notices.push(
					`claude-comm: ${tracked.length} file(s) of LIVE BUS STATE are committed to this project's git ` +
					`(${tracked.slice(0, 3).join(", ")}${tracked.length > 3 ? ", …" : ""}).\n` +
					`  .comm/ is inboxes, a delivery log and a lifecycle ledger - it changes every turn, it is per-machine, ` +
					`and committing it puts another agent's mail in your history.\n` +
					`  Fix:  git rm -r --cached .comm/   then add a line '.comm/' to .gitignore\n` +
					`  Why:  ${join(projectRoot, ".comm", "README.md")}`)
			}
		}
	} catch { /* a guard must never break a session */ }
	// IS THIS BUS OUT OF DATE, AND DOES ANYONE HERE KNOW? Until 2026-09-05 the answer to the
	// second half was no. The only thing on the machine that noticed an out-of-date field bus
	// was the claude-comm leader's own boot, because it scans sibling projects — so a project's
	// own agents had no signal at all, and updating depended on somebody remembering. The
	// owner asked for the opposite: *"il faut que l'outil soit facile à mettre à jour chez tous
	// les agents."* A mechanism, not a person's vigilance.
	//
	// It reads two small files and spawns nothing: this project's own `INSTALLED.json`, and
	// the source checkout's CHANGELOG heading. It speaks ONCE PER VERSION — the marker holds
	// the label it announced, so a new release says it again and an unchanged one never does.
	// A line printed at every start is a line nobody reads, which is the failure this whole
	// file keeps finding in its own output.
	//
	// EVERY branch is silent-and-harmless on failure except one: a source checkout that cannot
	// be read AT ALL is reported, because "I could not check" and "you are current" are
	// different answers and this project's rule is that a probe's silence is not evidence.
	try {
		const instP = join(projectRoot, ".comm", "INSTALLED.json")
		const mark = join(projectRoot, ".comm", ".update-seen")
		let mine = null
		try { mine = JSON.parse(readFileSync(instP, "utf8")) } catch {}
		if (mine && mine.from) {
			const clog = join(mine.from, "CHANGELOG.md")
			let head = null
			try {
				const first = readFileSync(clog, "utf8").split(/^## /m)[1] || ""
				const m = /^(\S+) — bus print `([0-9a-f]{12})`/.exec(first)
				if (m) head = { label: m[1], print: m[2] }
			} catch {}
			let said = ""
			try { said = readFileSync(mark, "utf8").trim() } catch {}
			if (!head) {
				// The checkout moved, was deleted, or its changelog is unreadable. Say it once,
				// keyed on the path, because an update command nobody can run is worth knowing.
				if (said !== `missing:${mine.from}`) {
					notices.push(`claude-comm: this bus is ${mine.label}, and I could NOT check whether it is current — ${clog} is unreadable or gone. That is not the same as being up to date.`)
					marks.push([mark, `missing:${mine.from}\n`])
				}
			// KEYED ON THE LABEL, NOT THE PRINT — and the first version keyed on the print,
			// which was measured saying *"your bus is 2026-09-05.1 and 2026-09-05.1 is
			// available"*. Two different conditions were being conflated:
			//   · the source carries a RELEASE this project does not have — the field's
			//     business, and what this line is for;
			//   · the source's bytes have moved past its own newest note — the MAINTAINER's
			//     business, reported by the installer to whoever runs it, and nothing a field
			//     agent can act on. It is normal for minutes at a time while a fix is written.
			// Announcing the second as if it were the first is a warning that fires during
			// ordinary work and names a version you already have.
			} else if (head.label !== String(mine.label).replace(/\+unreleased$/, "") && said !== head.label) {
				notices.push(
					`claude-comm: this project's bus is ${mine.label} and ${head.label} is available.\n` +
					`  what changed: ${clog}\n` +
					`  update:       node ${join(mine.from, "install.mjs")} ${projectRoot}\n` +
					`  said once for this version, not again.`)
				marks.push([mark, head.label + "\n"])
			}
		}
	} catch { /* a version check must never break a session */ }

// DELIVERY FIRST, and its status is this hook's status. Everything below is an
// instrument: it may not delay delivery, may not fail it, and may not change one byte
// of what the harness sees.
// Bounded HERE, on this side of spawn (review #12 A1): a NUL in one made spawnSync throw and a 140 kB one gave E2BIG,
// status null - the mail left waiting and nothing said so. And if the spawn fails anyway, deliver without them.
for (let i = 0; i < notices.length; i++) notices[i] = String(notices[i]).replace(/\u0000/g, "").slice(0, 1500)
let delivered = forward(raw, notices)
if (delivered.error && notices.length) {
	process.stderr.write(`claude-comm: the bus could not be started WITH its notices (${delivered.error.code || delivered.error.message}); delivering without them.\n`)
	delivered = forward(raw, [])
}
if (delivered.status === 0) for (const [f, c] of marks) { try { writeFileSync(f, c) } catch {} }

try {
	let p = {}
	try { p = JSON.parse(raw) } catch {}
	const binDir = dirname(bus)
	const tp = typeof p.transcript_path === "string" ? p.transcript_path : ""
	// The NAME comes from the bus, which is the one place identity is resolved. A
	// ledger keyed on a name this stub had guessed for itself would disagree with the
	// delivery log about who did what, and the ledger counts a `mislabelled` row for
	// exactly that reason. "unnamed" matches what boot records for an off-bus session:
	// a session that cannot be named is still a session that can author a defect.
	const agent = whoIs || "unnamed"

	// The registry: pid -> the transcript this session is writing NOW. An import rather
	// than a spawn, because it is one function call and cannot fail slowly. Without it
	// a context sensor answers with the session this process was LAUNCHED as, which
	// after a /clear is a dead one. FINDINGS.md#clear-blind
	// The result is READ, not dropped. This file's own contract says a registry that
	// silently did not write reads later as a machine with no sessions on it - and review
	// #5 found the only field caller discarding that reason inside a bare catch, which is
	// the enabling condition for a stale entry answering as if it were fresh. stderr,
	// never stdout: stdout carries the hook's JSON contract and one extra byte there
	// breaks delivery. record() is called even with NO transcript_path, because its first
	// act is to invalidate the entry this pid already had.
	// Whether this start belongs to a session in THIS project: false only when that is KNOWN to be untrue, so
	// the ledger below refuses a hand-fired stub (a probe, a test, another project's session) and still records
	// when the registry cannot be asked. Measured 2026-09-19: a probe of a brand-new project's stub, fired from
	// the claude-comm leader's session, wrote a phantom cold start into that project's ledger - the registry
	// refused it, the ledger had no such test.
	let ownStart = null
	try {
		const reg = join(binDir, "session-registry.mjs")
		if (existsSync(reg)) {
			const m = await import(pathToFileURL(reg).href)
			const sp = m.sessionPid()
			// 0 is "no claude ancestor found" (off Linux, another argv0): CANNOT TELL, so the ledger still records
			// (review #12 E1). Only a found session running outside this project is known to be foreign.
			ownStart = sp > 0 ? ownsSession(sp) : null
			if (!ownsSession(sp)) throw new Error(`the session I resolved (pid ${sp}) is not running inside ${projectRoot}; recording nothing`)
			const r = m.record({ pid: sp, transcript: tp, agent, source: p.source })
			if (!r.ok) process.stderr.write(`claude-comm: this session is NOT in the session registry (${r.why}). `
				+ `A context reading by pid will refuse for it${r.invalidated ? "" : ", and a previous entry may still stand"}.\n`)
		} else {
			process.stderr.write("claude-comm: session-registry.mjs is not installed beside the bus, so this session could not be recorded AND ANY PREVIOUS ENTRY FOR THIS PID STILL STANDS - a context reading by pid may answer for a session that has ended.\n")
		}
	} catch (e) {
		process.stderr.write(`claude-comm: the session registry could not be loaded (${(e && e.message) || e}), so this session could not be recorded AND ANY PREVIOUS ENTRY FOR THIS PID STILL STANDS - a context reading by pid may answer for a session that has ended.\n`)
	}




	// The ledger: the control arm for "did the fifteen minutes after a restart cost us
	// a defect". It records into THIS project, beside this project's bus, because this
	// is where the restarts being measured actually happen. Read it back with
	// `node bin/ledger.mjs --root <this project>`.
	// ONE RECORDER PER ROOT (review #11 R1, #11b S1/S2). In claude-comm's OWN checkout the
	// root's `bin/boot.mjs --hook` records from the code at HEAD and re-reads its write, so this
	// copy - one install behind - stands aside there. The test reads the file the hooks come
	// from; if it ever misses, both record and the ledger collapses the twin: never a lost start.
	// 🔴 THE HOOKS OF THIS AGENT'S DIRECTORY, never the root's (review #11c T1). A session in
	// `review/` loads `review/.claude/settings.json`, which runs only this stub: reading the
	// ROOT's file made every expert stand aside for a `boot --hook` that never runs for it, and
	// its starts stopped reaching the ledger with nothing to say so (measured: 0 records, 1 unwired).
	let rootRecords = false
	try {
		if (existsSync(join(projectRoot, "bin", "boot.mjs"))) {
			const st = JSON.parse(readFileSync(join(agentRoot, ".claude", "settings.json"), "utf8"))
			rootRecords = ((st && st.hooks && st.hooks.SessionStart) || []).some((g) => ((g && g.hooks) || [])
				.some((h) => h && typeof h.command === "string" && /bin\/boot\.mjs["']?\s+(?:--\S+\s+)*--hook\b/.test(h.command)))
		}
	} catch {}
	try {
		const led = join(binDir, "ledger.mjs")
		if (!rootRecords && ownStart !== false && existsSync(led) && p.source && tp) {
			// THE SIGNAL THAT CROSSES THE RESTART, claimed here and nowhere else. At this
			// hook a relaunch and a cold start are the same event — `source` is "startup"
			// for both — so without this the reboot arm of the experiment is not
			// under-filled, it is UNREACHABLE. FINDINGS.md#reboot-signal
			//
			// Claimed INSIDE the guard that records, so a signal is never consumed by a
			// hook that was not going to write a start: a one-shot note taken by a path
			// that then records nothing is a reboot silently filed as cold.
			let sig = []
			let rsMod = null, taken = null
			try {
				const rs = join(binDir, "restart-signal.mjs")
				if (existsSync(rs)) {
					const m = await import(pathToFileURL(rs).href)
					rsMod = m
					// Only a start that IS a fresh context takes the note (review #11 R2/R7): a
					// compaction or a resume records its start and leaves the note for the relaunch.
					const c = typeof m.mayClaim !== "function" || m.mayClaim(p.source)
						? m.claim({ root: projectRoot, agent }) : { ok: true, signal: null }
					if (c.ok && c.signal) taken = c.signal
					if (!c.ok) {
						// Never silent. A signal that could not be read is a restart about to be
						// recorded as a cold start, which is the exact defect this mechanism exists
						// to remove — and a bare catch here would hide it forever.
						process.stderr.write(`claude-comm: a restart signal for ${agent} could not be claimed (${c.why}); this start is being recorded as COLD.\n`)
					} else if (c.signal) {
						// Measurements only. Whether this age still counts is the ledger's
						// `classify()` to decide, so the rule stays correctable over records
						// already written. An age that could not be measured is OMITTED rather
						// than sent as a placeholder: the ledger refuses a non-numeric flag, and
						// refusing would cost the whole start record.
						if (c.signal.prev_session) sig.push("--prev-session", String(c.signal.prev_session))
						sig.push("--signal-src", String(c.signal.by || "unknown"))
						if (Number.isFinite(c.age_s)) sig.push("--signal-age", String(c.age_s))
						if (Number.isFinite(c.signal.ttl_s)) sig.push("--signal-ttl", String(c.signal.ttl_s))
						// The armer, measured at this claim (`FINDINGS.md#armer`): the ledger stores it and
						// `classify()` decides. Absent from an older restart-signal.mjs, and then omitted.
						if (c.armer && typeof c.armer.state === "string") sig.push("--signal-armer", c.armer.state)
						if (c.armer && Number.isFinite(c.armer.quiet_s)) sig.push("--signal-quiet", String(c.armer.quiet_s))
					}
				}
			} catch (e) {
				process.stderr.write(`claude-comm: the restart signal could not be loaded (${(e && e.message) || e}); this start is being recorded as COLD.\n`)
			}
			// --pending-auto: what was already waiting in front of this session when it
			// opened, counted by the ledger itself so there is one implementation of it.
			// The covariate the ~/Dev/work leader's measurement asked for, and it is HIS
			// definition, not the inbox depth I proposed - his session #41 had an empty
			// mailbox and a 246-line report on disk, so mine would have scored the busiest
			// boot of his last five as EMPTY. Priced before adopting: 14 of 891 files, 17 ms
			// on his tree. FINDINGS.md#reboot-signal
			const rec = spawnSync(process.execPath, [led, "record", "start", "--agent", agent,
				"--source", p.source, "--session", basename(tp).replace(/\.jsonl$/, ""),
				"--root", projectRoot, "--quiet", "--pending-auto", ...sig], { timeout: 5000, stdio: "ignore" })
			// A claim is destructive and a record is not retried. If the write failed after
			// the note was taken, that restart is gone and this line is the only thing that
			// will ever say so.
			if (sig.length && rec.status !== 0) {
				// Put it back (review #11 R3): a ledger that cannot load must not also eat the note.
				const back = taken && rsMod && typeof rsMod.restore === "function" ? rsMod.restore({ root: projectRoot, agent, record: taken }) : { ok: false, why: "nothing to restore with" }
				process.stderr.write(`claude-comm: a restart signal for ${agent} was claimed but the ledger did not record it (exit ${rec.status}); ${back.ok ? "the note was PUT BACK for the next start" : `that restart is now UNCOUNTED (${back.why})`}.\n`)
			}
		}
	} catch {}
} catch { /* an instrument must never break a session */ }

// 🔴 EXIT 0, ALWAYS — and say why when it is not zero. The bus's own main() wraps the
// hook in try/catch and exits 0 on every path, INCLUDING the block, which it signals with
// stdout JSON rather than a status. So a non-zero here cannot be a decision: it means the
// bus process never RAN — a missing module, a truncated file, a syntax error mid-install.
// Propagating it broke the turn, which is the one thing this project says a broken bus must
// never do. Measured 2026-09-11 on a half-installed tree: exit 1 and a Node stack trace.
// ⚠️ Loud AND non-breaking: the child's stderr is inherited, so its trace is already on
// screen; this line names what the status meant. Silence would be the worse defect.
if (delivered.status || delivered.error) {
	process.stderr.write(`claude-comm: the bus could not RUN (${delivered.error ? delivered.error.code || delivered.error.message : `exit ${delivered.status}`}) — the hook path exits 0 on every decision, so this is a broken or half-installed bus, not a verdict. Your mail is untouched and this turn is not blocked. Re-run the installer.\n`)
}
process.exit(0)
